name: sfbms_mobile
description: Sport Field Booking Management System.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.18.0

  firebase_auth: ^3.3.20

  google_sign_in: ^5.3.3

  http: ^0.13.4

  provider: ^6.0.3

  intl: ^0.17.0

  shared_preferences: ^2.0.15

  flutter_svg: ^1.1.0

  extended_image: ^6.2.1

  pull_to_refresh: ^2.0.0

  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_gen: ^4.3.0

  flutter_gen_runner:

  flutter_launcher_icons: "^0.9.3"

# cli: fluttergen -c pubspec.yaml
flutter_gen:
  integrations:
    flutter_svg: true

# cli: flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true

flutter:
  uses-material-design: true

  assets:
    # env
    - env/.env
    - env/development.env

    # image
    - assets/images/login_background.jpg
    - assets/images/logo_full.png
    - assets/images/logo.png

    # svg
    - assets/svgs/search.svg
    - assets/svgs/google.svg